/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import dao.ventaDAO;
import modelo.Venta;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;



/**
 *
 * @author esther
 */
public class IFrmReporte extends javax.swing.JInternalFrame {

    ventaDAO vd = new ventaDAO();
    public IFrmReporte() {
        initComponents();
        setSize(1200,553);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCat = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtanio = new javax.swing.JTextField();
        btnlineal = new javax.swing.JButton();
        pnlreporte = new javax.swing.JPanel();

        panelCat.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelCatLayout = new javax.swing.GroupLayout(panelCat);
        panelCat.setLayout(panelCatLayout);
        panelCatLayout.setHorizontalGroup(
            panelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        panelCatLayout.setVerticalGroup(
            panelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        jLabel1.setText("INGRESE AÑO");

        btnlineal.setText("LINEAL");
        btnlineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlinealActionPerformed(evt);
            }
        });

        pnlreporte.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlreporteLayout = new javax.swing.GroupLayout(pnlreporte);
        pnlreporte.setLayout(pnlreporteLayout);
        pnlreporteLayout.setHorizontalGroup(
            pnlreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );
        pnlreporteLayout.setVerticalGroup(
            pnlreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlreporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtanio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnlineal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlineal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlreporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlinealActionPerformed
        int an=Integer.parseInt(txtanio.getText());
        XYSeries series = new XYSeries("Datos");
        for(Venta v:vd.lisMes(an)){
           series.addOrUpdate(v.getMes(), v.getTotal()); 
        }
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(series);
        
        // Graficar en memoria
        JFreeChart lineChart = ChartFactory.createXYLineChart(
                "Gráfico Lineal de Ventas para el Año " + an, 
                "Meses", // Eje X
                "Total Ventas", // Etiqueta del eje Y
                dataset // Datos
        );
        ChartPanel cp = new ChartPanel(lineChart);
        pnlreporte.removeAll(); 
        pnlreporte.setLayout(new java.awt.BorderLayout());
        pnlreporte.add(cp);
        pnlreporte.validate();
        
    }//GEN-LAST:event_btnlinealActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlineal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelCat;
    private javax.swing.JPanel pnlreporte;
    private javax.swing.JTextField txtanio;
    // End of variables declaration//GEN-END:variables
}
